[simulation]
n_steps = 20
n_print = 10                      # Number of steps after which the positions are saved
n_flush = 1                       # Number of prints after which the output file is saved
time_step = 0.001                 # Inner loop timestep (for the fast forces); ps, 1 fs default set
respa_inner = 1                   # Number of inner loop steps. Therefore the timestep for the outer loop is given by (time_step * respa_inner)
cancel_com_momentum = true        # Whether to remove the center of mass momentum

# temperature
thermostat = "v-rescale"          # Bussi-Donadio-Parrinello implemented
start_temperature = 0             # Initial temperature
target_temperature = 300.0        # Thermostat target temperature
tau = 0.5                         # Thermostat coupling constant
thermostat_coupling_groups = [
    ['c3', 'h1', 'ca', 'ha', 'h4', 'h5', 'c', 'o', 'os', 'oh', 'ho'],
]

#PRESSURE
pressure = false
barostat = "no"

#ELECTROSTATIC
coulombtype = "pme"
#coulombtype = "reaction-field"
dielectric_const = 1.0
epsilon_rf = 80


#NON_BONDED CUT-OFFs
rv = 1.1
rc = 0.9
rlj = 0.9
ns_nlist = 10                     #number of n. steps between the trial update of Verlet list
nrexcl = 3                        #3 for automatic exclusion if 1-4 int (2 for manual, CHARMM)
skin = 0.2                        #Buffer for Verlet list (Default is skin/2 for V.List)


[atomistic_ff]
ff_family = "amber_like"
combining_rule = "lorentz-berthelot"
lj_input_source = "mixing"
coulomb14_scale = 0.8333333333
lj14_scale = 0.5
constrain_xh_bonds = false
ensemble = "NVT"


[field]
mesh_size = [60, 60, 60]          # FFT mesh grid. Only use even numbers with Diff-HyMD & TUNE it!
kappa = 0.05                      # Compressibilty
sigma = 0.5                       # Particle spread
rho0 = 8.86                       # Particle 'volume'. Optimized value for NPT
a = 9.21                          # Free parameter to fit water density. Optimized value for NPT
LJ_type_param = [                 #LJ presi da AMBER14SB
    [ 'Br',    4.65e-01,  2.45e-01   ],
    [ 'C',     3.40e-01,  3.60e-01   ],
    [ 'CA',    3.40e-01,  3.60e-01   ],
    [ 'CB',    3.40e-01,  3.60e-01   ],
    [ 'CC',    3.40e-01,  3.60e-01   ],
    [ 'CD',    3.40e-01,  3.60e-01   ],
    [ 'CI',    3.40e-01,  4.58e-01   ],
    [ 'CE',    3.40e-01,  4.58e-01   ],
    [ 'CK',    3.40e-01,  3.60e-01   ],
    [ 'CM',    3.40e-01,  3.60e-01   ],
    [ 'CN',    3.40e-01,  3.60e-01   ],
    [ 'CO',    3.40e-01,  3.60e-01   ],
    [ 'CP',    3.40e-01,  3.60e-01   ],
    [ 'CQ',    3.40e-01,  3.60e-01   ],
    [ 'CR',    3.40e-01,  3.60e-01   ],
    [ 'CS',    3.40e-01,  3.60e-01   ],
    [ 'CT',    3.40e-01,  4.58e-01   ],
    [ 'CV',    3.40e-01,  3.60e-01   ],
    [ 'CW',    3.40e-01,  3.60e-01   ],
    [ 'CX',    3.40e-01,  4.58e-01   ],
    [ 'CY',    3.40e-01,  3.60e-01   ],
    [ 'CZ',    3.40e-01,  3.60e-01   ],
    [ 'C*',    3.40e-01,  3.60e-01   ],
    [ 'C4',    3.40e-01,  3.60e-01   ],
    [ 'C1',    3.40e-01,  3.60e-01   ],
    [ 'C2',    3.40e-01,  3.60e-01   ],
    [ 'C5',    3.40e-01,  3.60e-01   ],
    [ 'C8',    3.40e-01,  4.58e-01   ],
    [ '2C',    3.40e-01,  4.58e-01   ],
    [ '3C',    3.40e-01,  4.58e-01   ],
    [ 'C0',    3.05e-01,  1.92e+00   ],
    [ 'F',     3.12e-01,  2.55e-01   ],
    [ 'H',     1.07e-01,  6.57e-02   ],
    [ 'HO',    0.00e+00,  0.00e+00   ],
    [ 'HS',    1.07e-01,  6.57e-02   ],
    [ 'HC',    2.65e-01,  6.57e-02   ],
    [ 'H1',    2.47e-01,  6.57e-02   ],
    [ 'H2',    2.29e-01,  6.57e-02   ],
    [ 'H3',    2.11e-01,  6.57e-02   ],
    [ 'HP',    1.96e-01,  6.57e-02   ],
    [ 'HA',    2.60e-01,  6.28e-02   ],
    [ 'H4',    2.51e-01,  6.28e-02   ],
    [ 'H5',    2.42e-01,  6.28e-02   ],
    [ 'HW',    0.00e+00,  0.00e+00   ],
    [ 'HZ',    2.60e-01,  6.28e-02   ],
    [ 'I',     5.10e-01,  2.25e-01   ],
    [ 'Cl',    4.48e-01,  1.49e-01   ],
    [ 'Na',    2.44e-01,  3.66e-01   ],
    [ 'MG',    1.41e-01,  3.74e+00   ],
    [ 'N',     3.25e-01,  7.11e-01   ],
    [ 'NA',    3.25e-01,  7.11e-01   ],
    [ 'NB',    3.25e-01,  7.11e-01   ],
    [ 'NC',    3.25e-01,  7.11e-01   ],
    [ 'N2',    3.25e-01,  7.11e-01   ],
    [ 'N3',    3.25e-01,  7.11e-01   ],
    [ 'NT',    3.25e-01,  7.11e-01   ],
    [ 'N*',    3.25e-01,  7.11e-01   ],
    [ 'NY',    3.25e-01,  7.11e-01   ],
    [ 'O',     2.96e-01,  8.79e-01   ],
    [ 'O2',    2.96e-01,  8.79e-01   ],
    [ 'OW',    3.15e-01,  6.36e-01   ],
    [ 'OH',    3.07e-01,  8.80e-01   ],
    [ 'OS',    3.00e-01,  7.11e-01   ],
    [ 'OP',    3.30e-01,  7.11e-01   ],
    [ 'P',     3.74e-01,  8.37e-01   ],
    [ 'S',     3.56e-01,  1.05e+00   ],
    [ 'SH',    3.56e-01,  1.05e+00   ],
    [ 'CU',    3.40e-01,  3.60e-01   ],
    [ 'FE',    0.00e+00,  0.00e+00   ],
    [ 'K',     3.04e-01,  8.10e-01   ],
    [ 'Rb',    3.23e-01,  1.37e+00   ],
    [ 'Cs',    3.52e-01,  1.70e+00   ],
    [ 'IB',    8.91e-01,  4.18e-01   ],
    [ 'EP',    0.00e+00,  0.00e+00   ],
    [ 'OW_spc', 3.17e-01,  6.51e-01   ],
    [ 'HW_spc', 0.00e+00,  0.00e+00   ],
    [ 'Li',    2.03e-01,  7.66e-02   ],
    [ 'Zn',    1.96e-01,  5.23e-02   ],
    [ 'HW_tip4pew', 0.00e+00,  0.00e+00   ],
    [ 'OW_tip4pew', 3.16e-01,  6.81e-01   ],
    [ 'HW_tip4p', 0.00e+00,  0.00e+00   ],
    [ 'OW_tip4p', 3.15e-01,  6.49e-01   ],
    [ 'HW_tip5p', 0.00e+00,  0.00e+00   ],
    [ 'OW_tip5p', 3.12e-01,  6.69e-01   ],
    [ 'MW',    0.00e+00,  0.00e+00   ],
    [ 'MCH3',  0.00e+00,  0.00e+00   ],
    [ 'MNH3',  0.00e+00,  0.00e+00   ],
    # --- CUSTOM LIGAND TYPES --- 
    [ 'c3',    0.3398,  0.4510   ],
    [ 'h1',    0.2422,  0.0870   ],
    [ 'h1',    0.2422,  0.0870   ],
    [ 'h1',    0.2422,  0.0870   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'ha',    0.2625,  0.0674   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'h4',    0.2536,  0.0674   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'ha',    0.2625,  0.0674   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'h5',    0.2447,  0.0674   ],
    [ 'c',    0.3315,  0.4134   ],
    [ 'o',    0.3048,  0.6121   ],
    [ 'os',    0.3156,  0.3038   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'ca',    0.3315,  0.4134   ],
    [ 'c',    0.3315,  0.4134   ],
    [ 'o',    0.3048,  0.6121   ],
    [ 'oh',    0.3243,  0.3891   ],
    [ 'ho',    0.0538,  0.0197   ],
]















































































































































































































































































































































































































































































































































































