[simulation]
n_steps = 1000                    # Number of outer steps
n_print = 1                       # Number of steps after which the positions are saved
n_flush = 1                       # Number of prints after which the output file is saved
time_step = 0.02                  # Inner loop timestep (for the fast forces)
respa_inner = 10                  # Number of inner loop steps. Therefore the timestep for the outer loop is given by (time_step * respa_inner)
cancel_com_momentum = true        # Whether to remove the center of mass momentum

# electrostatics
dielectric_const = 60.0
coulombtype = 'PIC_Spectral'

# temperature
start_temperature = 323           # Initial temperature
target_temperature = 323          # Thermostat target temperature
tau = 0.1                         # Thermostat coupling constant
thermostat_coupling_groups = [
    ['Qd', 'P1', 'P5', 'N0', 'C1', 'SC4', 'SP1', 'Nda', 'Qa', 'P4', 'C5', 'Nd',
 'SC5', 'Na', 'C2', 'C3', 'SNd'],
    ['W', 'NA', 'CL'],
]

# pressure
pressure = true                   # Whether pressure coupling is on 
barostat_type = 'berendsen'       # Barostat type
barostat = 'isotropic'            # Barostat coupling
tau_p = 0.1                       # Barostat coupling constant
target_pressure = 1               # Barostat target pressure
# barostat = 'berendsen'          # In Diff-HyMD, these two options are reversed
# barostat_type = 'isotropic'     # 

[field]
mesh_size = [20, 20, 20]          # FFT mesh grid. Only use even numbers with Diff-HyMD!
kappa = 0.05                      # Compressibilty
sigma = 0.5                       # Particle spread
rho0 = 8.86                       # Particle 'volume'. Optimized value for NPT
a = 9.21                          # Free parameter to fit water density. Optimized value for NPT
chi = [                           # Type-type interation matrix
    # ['A','A', 0.0] => No need to specify self-interactions, assumed to be 0.0
    [   'Qd',    'P1',    10],
    [   'Qd',    'P5',    10],
    [   'Qd',    'N0',    10],
    [   'Qd',    'C1',    10],
    [   'Qd',   'SC4',    10],
    [   'Qd',   'SP1',    10],
    [   'Qd',   'Nda',    10],
    [   'Qd',    'Qa',    10],
    [   'Qd',    'P4',    10],
    [   'Qd',    'C5',    10],
    [   'Qd',    'Nd',    10],
    [   'Qd',   'SC5',    10],
    [   'Qd',    'Na',    10],
    [   'Qd',    'C2',    10],
    [   'Qd',    'C3',    10],
    [   'Qd',   'SNd',    10],
    [   'Qd',     'W',    10],
    [   'Qd',    'NA',    10],
    [   'Qd',    'CL',    10],
    [   'P1',    'P5',    10],
    [   'P1',    'N0',    10],
    [   'P1',    'C1',    10],
    [   'P1',   'SC4',    10],
    [   'P1',   'SP1',    10],
    [   'P1',   'Nda',    10],
    [   'P1',    'Qa',    10],
    [   'P1',    'P4',    10],
    [   'P1',    'C5',    10],
    [   'P1',    'Nd',    10],
    [   'P1',   'SC5',    10],
    [   'P1',    'Na',    10],
    [   'P1',    'C2',    10],
    [   'P1',    'C3',    10],
    [   'P1',   'SNd',    10],
    [   'P1',     'W',    10],
    [   'P1',    'NA',    10],
    [   'P1',    'CL',    10],
    [   'P5',    'N0',    10],
    [   'P5',    'C1',    10],
    [   'P5',   'SC4',    10],
    [   'P5',   'SP1',    10],
    [   'P5',   'Nda',    10],
    [   'P5',    'Qa',    10],
    [   'P5',    'P4',    10],
    [   'P5',    'C5',    10],
    [   'P5',    'Nd',    10],
    [   'P5',   'SC5',    10],
    [   'P5',    'Na',    10],
    [   'P5',    'C2',    10],
    [   'P5',    'C3',    10],
    [   'P5',   'SNd',    10],
    [   'P5',     'W',    10],
    [   'P5',    'NA',    10],
    [   'P5',    'CL',    10],
    [   'N0',    'C1',    10],
    [   'N0',   'SC4',    10],
    [   'N0',   'SP1',    10],
    [   'N0',   'Nda',    10],
    [   'N0',    'Qa',    10],
    [   'N0',    'P4',    10],
    [   'N0',    'C5',    10],
    [   'N0',    'Nd',    10],
    [   'N0',   'SC5',    10],
    [   'N0',    'Na',    10],
    [   'N0',    'C2',    10],
    [   'N0',    'C3',    10],
    [   'N0',   'SNd',    10],
    [   'N0',     'W',    10],
    [   'N0',    'NA',    10],
    [   'N0',    'CL',    10],
    [   'C1',   'SC4',    10],
    [   'C1',   'SP1',    10],
    [   'C1',   'Nda',    10],
    [   'C1',    'Qa',    10],
    [   'C1',    'P4',    10],
    [   'C1',    'C5',    10],
    [   'C1',    'Nd',    10],
    [   'C1',   'SC5',    10],
    [   'C1',    'Na',    10],
    [   'C1',    'C2',    10],
    [   'C1',    'C3',    10],
    [   'C1',   'SNd',    10],
    [   'C1',     'W',    10],
    [   'C1',    'NA',    10],
    [   'C1',    'CL',    10],
    [  'SC4',   'SP1',    10],
    [  'SC4',   'Nda',    10],
    [  'SC4',    'Qa',    10],
    [  'SC4',    'P4',    10],
    [  'SC4',    'C5',    10],
    [  'SC4',    'Nd',    10],
    [  'SC4',   'SC5',    10],
    [  'SC4',    'Na',    10],
    [  'SC4',    'C2',    10],
    [  'SC4',    'C3',    10],
    [  'SC4',   'SNd',    10],
    [  'SC4',     'W',    10],
    [  'SC4',    'NA',    10],
    [  'SC4',    'CL',    10],
    [  'SP1',   'Nda',    10],
    [  'SP1',    'Qa',    10],
    [  'SP1',    'P4',    10],
    [  'SP1',    'C5',    10],
    [  'SP1',    'Nd',    10],
    [  'SP1',   'SC5',    10],
    [  'SP1',    'Na',    10],
    [  'SP1',    'C2',    10],
    [  'SP1',    'C3',    10],
    [  'SP1',   'SNd',    10],
    [  'SP1',     'W',    10],
    [  'SP1',    'NA',    10],
    [  'SP1',    'CL',    10],
    [  'Nda',    'Qa',    10],
    [  'Nda',    'P4',    10],
    [  'Nda',    'C5',    10],
    [  'Nda',    'Nd',    10],
    [  'Nda',   'SC5',    10],
    [  'Nda',    'Na',    10],
    [  'Nda',    'C2',    10],
    [  'Nda',    'C3',    10],
    [  'Nda',   'SNd',    10],
    [  'Nda',     'W',    10],
    [  'Nda',    'NA',    10],
    [  'Nda',    'CL',    10],
    [   'Qa',    'P4',    10],
    [   'Qa',    'C5',    10],
    [   'Qa',    'Nd',    10],
    [   'Qa',   'SC5',    10],
    [   'Qa',    'Na',    10],
    [   'Qa',    'C2',    10],
    [   'Qa',    'C3',    10],
    [   'Qa',   'SNd',    10],
    [   'Qa',     'W',    10],
    [   'Qa',    'NA',    10],
    [   'Qa',    'CL',    10],
    [   'P4',    'C5',    10],
    [   'P4',    'Nd',    10],
    [   'P4',   'SC5',    10],
    [   'P4',    'Na',    10],
    [   'P4',    'C2',    10],
    [   'P4',    'C3',    10],
    [   'P4',   'SNd',    10],
    [   'P4',     'W',    10],
    [   'P4',    'NA',    10],
    [   'P4',    'CL',    10],
    [   'C5',    'Nd',    10],
    [   'C5',   'SC5',    10],
    [   'C5',    'Na',    10],
    [   'C5',    'C2',    10],
    [   'C5',    'C3',    10],
    [   'C5',   'SNd',    10],
    [   'C5',     'W',    10],
    [   'C5',    'NA',    10],
    [   'C5',    'CL',    10],
    [   'Nd',   'SC5',    10],
    [   'Nd',    'Na',    10],
    [   'Nd',    'C2',    10],
    [   'Nd',    'C3',    10],
    [   'Nd',   'SNd',    10],
    [   'Nd',     'W',    10],
    [   'Nd',    'NA',    10],
    [   'Nd',    'CL',    10],
    [  'SC5',    'Na',    10],
    [  'SC5',    'C2',    10],
    [  'SC5',    'C3',    10],
    [  'SC5',   'SNd',    10],
    [  'SC5',     'W',    10],
    [  'SC5',    'NA',    10],
    [  'SC5',    'CL',    10],
    [   'Na',    'C2',    10],
    [   'Na',    'C3',    10],
    [   'Na',   'SNd',    10],
    [   'Na',     'W',    10],
    [   'Na',    'NA',    10],
    [   'Na',    'CL',    10],
    [   'C2',    'C3',    10],
    [   'C2',   'SNd',    10],
    [   'C2',     'W',    10],
    [   'C2',    'NA',    10],
    [   'C2',    'CL',    10],
    [   'C3',   'SNd',    10],
    [   'C3',     'W',    10],
    [   'C3',    'NA',    10],
    [   'C3',    'CL',    10],
    [  'SNd',     'W',    10],
    [  'SNd',    'NA',    10],
    [  'SNd',    'CL',    10],
    [    'W',    'NA',    10],
    [    'W',    'CL',    10],
    [   'NA',    'CL',    10],
]
