[nn]
systems = ["dppc"]          # list of directories of the systems that need to be trained
n_epochs = 150              # Number of training iterations
equilibration = 5000        # Whether to run N equilibration steps before the differentiable dynamics
teacher_forcing = false     # Whether to use the last positions and velocities as starting point for the next epoch
chain = false               # Whether to chain different optimizers, see example below
shuffle = true              # Whether to shuffle the indices of dataset at the start of each epoch. 
batch_size = 1

[nn.optimizer]
name = 'adabelief'          # Name of the optimizer, refer to the optax documentation (https://optax.readthedocs.io/en/latest/api.html) 
                            # to check the available optimizers and their options                                                     
learning_rate = 0.1         # Can also be replaced with a LR scheduler, see below
b1 = 0.1                    # Example optimizer options
b2 = 0.4

# Example with LR scheduler, refer to the optax documentation for the available schedulers
# [nn.optimizer.learning_rate]
# schedule = "exponential_decay"
# init_value = 5
# transition_steps = 200
# decay_rate = 0.98
# transition_begin = 10

# Example when chaining multiple optax transformations
# chain = true
# [[nn.optimizer]] # double brackets are needed!
# name = 'clip'
# max_delta = 1e3

# [[nn.optimizer]]
# name = 'sgd'
# learning_rate = 1e-2

# This section specifies the loss function and its parameters
[nn.loss]
name = 'density_and_apl'               # Only 'density_and_apl' is available right now             
metric = "mse"                         # Availble options: 'mse', 'rmse', 'smape', 'l2e' (L2 loss) 

# optional parameters
width_ratio = 0.5        # Gaussian KDE width
density_weight = 1       # Weight of the lateral density       
apl_weight = 1         # Weight of the Area Per Lipid
# constraint = "harmonic"     # Individual chi pairs constraints, see below
# k_constraint = 0.1      # Strength of the constraint

# System sepcific loss arguments (can be mixed-matched with the ones above for better control)
[nn.system_args.dppc]
com_type = "C1"          # Type selection for the COM calculation
n_lipids = 64            # Number of lipids in the system
target_apl = 0.633       # Target Area Per Lipid value
target_density = "reference_aa.xvg"    # Reference all-atom density profiles

[nn.model]
LJ_param = [
[ 'Q1', 'Q5', 4.70e-01, 3.79 , 'on' ],
[ 'SN4a', 'SN4a', 4.10e-01, 2.60, 'on'],
[ 'N4a', 'N4a', 4.70e-01, 3.39, 'on' ],
[ 'C1', 'C1', 4.70e-01, 2.39, 'on' ],
[ 'W', 'W', 4.70e-01, 4.65],
[ 'C1', 'N4a', 4.70e-01, 2.79 ],
[ 'C1', 'Q1', 4.85e-01, 2.578 ],
[ 'C1', 'Q5', 6.20e-01, 2.046 ],
[ 'C1', 'SN4a', 4.30e-01, 2.16 ],
[ 'C1', 'W', 4.70e-01, 2.06 ],
[ 'N4a', 'Q1', 4.70e-01, 2.726, 'on' ],
[ 'N4a', 'Q5', 4.70e-01, 1.887, 'on' ],
[ 'N4a', 'SN4a', 4.30e-01, 2.93, 'on' ],
[ 'N4a', 'W', 4.65e-01, 3.50 ],
[ 'Q1', 'Q1', 4.70e-01, 3.98 ],
[ 'Q1', 'SN4a', 4.30e-01, 4.236 ],
[ 'Q1', 'W', 4.65e-01, 1.22 ],
[ 'Q5', 'Q5', 4.70e-01, 6.45 ],
[ 'Q5', 'SN4a', 4.30e-01, 4.386 ],
[ 'Q5', 'W', 4.65e-01, 6.34 ],
[ 'SN4a', 'W', 4.25e-01, 3.00 ],
]

