[simulation]
n_steps = 1000
n_print = 1                     # Number of steps after which the positions are saved
n_flush = 1                     # Number of prints after which the output file is saved
time_step = 0.0005               # Inner loop timestep (for the fast forces) ps, 0.5 fs
respa_inner =  1                # Number of inner loop steps. Therefore the timestep for the outer loop is given by (time_step * respa_inner)
cancel_com_momentum = true      # Whether to remove the center of mass momentum

# temperature
start_temperature = false
target_temperature = 310.15          # Thermostat target temperature
tau = 1.0                            # Thermostat coupling constant
thermostat_coupling_groups = [
    ['C1', 'N4a', 'Q1', 'Q5', 'SN4a'],
    ['W'],
]

# pressure
pressure = false
barostat = "no"
#pressure = true                   # Whether pressure coupling is on 
#barostat = 'berendsen'            # Barostat name
#barostat_type = 'semiisotropic'   # Barostat type ("isotropic", "semiisotropic")
#tau_p = 4.0                       # Barostat coupling constant
#target_pressure = [1.0, 1.0]      # Barostat target pressure
#beta = 3.5e-5

# NON BONDED (LJ & PME)
coulombtype = "reaction-field"    # "pme"
#elec_conversion = 138.935458
dielectric_const = 15             # Relative dielectric constant
epsilon_rf = 80                   # Relative dielectric constant for reaction-field, if 0 - epsilonrf = infinite
rv = 1.2			  # Cutoff for Verlet list
rc = 1.1			  # Cutoff for electrostatic interation
rlj = 1.1			  # Cutoff for Lennard-Jones interaction
ns_nlist = 10			  # Number of steps to Verlet list update 
nrexcl = 1			  # Number of excluded bonded neighbors

[atomistic_ff]
ff_family = "amber_like"
combining_rule = "pairtable"
coulomb14_scale = 0.8333333333
lj14_scale = 0.5
constrain_xh_bonds = false
ensemble = "NVT"
[field]
mesh_size = [20, 20, 20]          # FFT mesh grid. Only use even numbers with Diff-HyMD!
kappa = 0.05                      # Compressibilty
sigma = 0.5                       # Particle spread
rho0 = 8.86                       # Particle 'volume'. Optimized value for NPT
a = 9.21                          # Free parameter to fit water density. Optimized value for NPT
LJ_param = [
[ 'Q1', 'Q5', 4.70e-01, 3.79e+00 ],
[ 'SN4a', 'SN4a', 4.10e-01, 2.60e+00 ],
[ 'N4a', 'N4a', 4.70e-01, 3.39e+00 ],
[ 'C1', 'C1', 4.70e-01, 3.39e+00 ],
[ 'W', 'W', 4.70e-01, 4.65e+00 ],
[ 'C1', 'N4a', 4.70e-01, 2.79e+00 ],
[ 'C1', 'Q1', 4.85e-01, 2.578e+00 ],
[ 'C1', 'Q5', 6.20e-01, 2.046e+00 ],
[ 'C1', 'SN4a', 4.30e-01, 2.16e+00 ],
[ 'C1', 'W', 4.70e-01, 2.06e+00 ],
[ 'N4a', 'Q1', 4.70e-01, 4.726e+00 ],
[ 'N4a', 'Q5', 4.70e-01, 4.887e+00 ],
[ 'N4a', 'SN4a', 4.30e-01, 2.93e+00 ],
[ 'N4a', 'W', 4.65e-01, 3.50e+00 ],
[ 'Q1', 'Q1', 4.70e-01, 3.98e+00 ],
[ 'Q1', 'SN4a', 4.30e-01, 4.236e+00 ],
[ 'Q1', 'W', 4.65e-01, 5.22e+00 ],
[ 'Q5', 'Q5', 4.70e-01, 6.45e+00 ],
[ 'Q5', 'SN4a', 4.30e-01, 4.386e+00 ],
[ 'Q5', 'W', 4.65e-01, 6.34e+00 ],
[ 'SN4a', 'W', 4.25e-01, 3.00e+00 ],
["C", "C", 0.34, 0.45],
["C", "N", 0.33, 0.40],
["C", "O", 0.32, 0.42],
["C", "H", 0.25, 0.10],
["N", "N", 0.32, 0.35],
["N", "O", 0.31, 0.38],
["N", "H", 0.24, 0.08],
["O", "O", 0.30, 0.30],
["O", "H", 0.23, 0.07],
["H", "H", 0.20, 0.02],
]

